### ISSUE TITLE
Daydream controller at first doesn't work, adds to user height and doesn't click when it does

### ISSUE THREAD

**Issue by Kezzsim** [wmurphyrd/aframe-super-hands-component#126]
Hi, I've been using SuperHands with a Vive ([to make this thing](http://apps.tlt.stonybrook.edu/hanoi/)) and its' fantastic!

But I'm having an absolutely terrible time getting it to work at all with the Daydream controller and my Pixel XL. I've tested it with the SuperHands Examples and with my own app, across Chrome Canary 67.0.3365 and Chrome 65.0.03365.
Android Version is 8.1.10
VR Services 1.13.185
Daydream app is same version
web-vr and gamepad flags are enabled

Initially, either placing the device into the Daydream or clicking the launch VR button gets the page into full screen stereoscopic VR mode; but no daydream controller appears.
The only way to get it to show up is to take the phone out of the headset, hit the back button on the phone (it goes back to the browser with the page in non-VR mode) and the daydream controller miraculously appears.

But...

Now the camera position is elevated by roughly 10 A-frame units, you have to look down on the scene from above. Even after recalibrating by holding the Daydream's home button, the controller's position is kinda off, it can't really point down that well, but when you can point down - the laser raycaster does select objects BUT clicking on the Daydream Controller's select pad does nothing (the 3D model of the controller shows the button lighting up but no actual click event fires)

I've restarted the phone several times and I've just been finding this frustrating, it's a problem I've had with all the A-Frame daydream compatible pages.

If this is a broader A-Frame problem, let me know so I can crosspost or link to it somehow.
Thanks for looking into it and developing this fantastic component~

**Comment by wmurphyrd** [comment]
Hi there. The height change is an issue in A-Frame (aframevr/aframe#3051). It's been solved, but won't be in a release version until v0.8.0 is out. You may also have noticed when using a raycaster-based interaction in your app that some rings get stuck in a "hovered" state so that you keep picking them up even when you're not pointing at them. This is also an A-Frame issue that has been solved but not yet released. You could test with the master branch of A-Frame to get past these issues - I've made some updates to keep `super-hands` compatible with that version that I'll be publishing soon. 

I haven't heard of the controller not appearing, but I've never had a chance to test with daydream myself. What happens if you power the controller off and back on while in VR mode? It's the `'controllerconnected'` event that triggers the model to load and `super-hands` to turn on the laser pointer.

**Comment by wmurphyrd** [comment]
Here's an alternative fix I've used in the past for the height:

```
AFRAME.registerComponent('setup', {
  init: function () {
    this.el.addEventListener('enter-vr', function (evt) {
      if (AFRAME.utils.device.isMobile() || AFRAME.utils.device.isGearVR()) {
        // fix A-Frame bug where mobile user height gets doubled
        cam.setAttribute('camera', {userHeight: 0.8})
      }
    })
  }
})
```

Then add `setup` to your `a-scene` entity.
