### ISSUE TITLE
Customizing interactivity

### ISSUE THREAD

**Issue by weddingdj** [wmurphyrd/aframe-super-hands-component#161]
Hi, I am using the code from the example index-laser and I would like to know how I could customize interactivity? I would like to rotate my entity around a fixed point (I am inside a carousel in my scene). Is there an example for this kind of customization? Or could you give a quick hint how to start? Thanks!

**Comment by wmurphyrd** [comment]
I would start by copying `grabbable` and making a custom reaction component. If you're using physics, you can get an effect like this by having your carousel as a dynamic body, placing a static body at its center and binding them together with a point-to-point constraint, and then just modifying grabbable to use a point-to-point constraint type instead of a lock constraint.

That would give free 360 rotation, for a single axis spin swap out the constraint inside the carousel for a hings constraint.
