### ISSUE TITLE
Moving Text entity in A-Frame

### ISSUE THREAD

**Issue by JeffreyConnected** [wmurphyrd/aframe-super-hands-component#173]
https://stackoverflow.com/questions/63063100/moving-text-entity-in-a-frame

**Comment by radicalappdev** [comment]
I ran into this issue as well, but I don't think it's a super-hands issue. When I made a scene using the grab component from aframe-extras instead of super-hands I ran into the same behavior. I *think* it is happening in the physics system, as these objects can be moved by other physics objects either. I filed an [issue](https://github.com/n5ro/aframe-physics-system/issues/181) on the physics repo.

**Comment by wmurphyrd** [comment]
Here's an example of a box with text that's movable with super-hands & physics (via mouse): https://glitch.com/edit/#!/past-sophisticated-mojoceratops?path=index.html%3A1%3A1

This is using racyaster for collision detection. I suspect your issues are related to the collision detection & the text component interfering with automatic shape generation. Try using the shape component to explicitly define the collision geometry.
