### ISSUE TITLE
Grab objects

### ISSUE THREAD

**Issue by andreiciungan** [wmurphyrd/aframe-super-hands-component#73]
Hello,

I would like to grab and move objects horizontally on the scene at the event 'mousedown' and without the camera to be centered on the object. I tried to use progressive controls, but there I can't select an object just with the mouse, I need to put the camera to be in the middle of the object. Anyway the object is moving around camera and I would like to move it anywhere on the scene. Is that possible to do it? Because I couldn't find how to solve it. Thank you.

**Comment by wmurphyrd** [comment]
The hard part here is defining what is means by "horizontally". You're talking about a direction in relation to the 2D canvas which holds a projection of the 3D world. To get an entity to track with the mouse's 2D location, you'd need to do the math to translate the cursor position into 3D space.

If you can do that, then its just a matter of putting `super-hands` on an entity that tracks with the mouse's 3d-translated position and setting the collider event properties.

**Comment by wmurphyrd** [comment]
P.S. I thought we might be able to leech off of the mouse cursor math used in the A-Frame core `cursor`, but it turns out they have the ray start from the camera center and point through the mouse (rather than start from the mouse and point straight into the scene), so the effect is not what you want, but this template might be helpful if you decide to sort out the math: https://glitch.com/edit/#!/exclusive-belief
