### ISSUE TITLE
Missing buttons-proto.js

### ISSUE THREAD

**Issue by HAZARDU5** [wmurphyrd/aframe-super-hands-component#93]
I've installed `super-hands` v2.0.1 from npm, however it's throwing the following error during compilation:

```
Error: Cannot find module 'buttons-proto.js' from '/Users/michael/Sites/district-tool/node_modules/super-hands/reaction_components'
```

Looks like this file is missing from the repo - is it a missing dependency?

Interestingly, using the current build from the `dist` folder in the master branch of the repository seems to work as expected.

**Comment by wmurphyrd** [comment]
[Well, shit](https://stackoverflow.com/a/34945604). 

I put those in `node_modules` because I couldn't get the package to build in both local and Travis-CI when referencing them with relative paths, but now that means npm will never include them in distributions. 

Any advice on how to include common code in multiple files?

**Comment by HAZARDU5** [comment]
Hmm... shouldn't common code files go into a folder in your source path? I'm not terribly familiar with Travis-CI, but I assume relative paths should be OK as it'll detect the included code as being the same and won't double up, even if the relative path is slightly different. I usually reserve `node_modules` only for stuff that's registered in `package.json` so everything's OK when committed into git repos.

**Comment by HAZARDU5** [comment]
Thanks, works great now! :-)
